name: CDRO-CLI Build
on:
  push:
    tags:
      - '*'
jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: ./build.sh
      - name: version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: version
      - name: release
        uses: Roang-zero1/github-create-release-action@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
      - name: upload artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
        with:
          args: "./artifacts/cdro-cli-*"
