name: CDRO-CLI Build
on:
  push:
    tags:
      - '*'
jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: ./build.sh
      - name: version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: version
      - name: changelog
        run: git log $(git describe --tags --abbrev=0 @^) --color --pretty=format:'%h%Creset %Creset %s'
        #######################################################
        # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token:  ${{ secrets.MYTOKEN }}
          body: "`git log $(git describe --tags --abbrev=0 @^) --color --pretty=format:'%h%Creset %Creset %s'`"
          files: |
            artifacts/cdro-cli-linux-386
            artifacts/cdro-cli-windows-386.exe
            artifacts/cdro-cli-windows-amd64.exe
            artifacts/cdro-cli-darwin-amd64
            artifacts/cdro-cli-darwin-arm64
            artifacts/cdro-cli-linux-amd64
