name: CDRO-CLI Build
on:
  push:
    tags:
      - '*'
jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: ./build.sh
      - name: version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: version

      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/*




