name: CDRO-CLI Build
on:
  push:
    tags:
      - '*'
jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: ./build.sh
      - name: version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: version

      - uses: SierraSoftworks/gh-releases@v1.0.7
        name: public-artifacts
        with:
          token: ${{ secrets.MYTOKEN }}
          overwrite: 'true'
          files: |
            ./artifacts/*



